spring:
  profiles:
    default: prod
---
#배포용 설정
spring:
  config:
    activate:
      on-profile: prod

  application:
    name: api-gateway

logging:
  file:
    path: /var/www/api-gateway
  level:
    root: info

server:
  port: 8080
  servlet:
    context-path: /

zylo:
  endpoints:
    excluded-paths:
      - /v1/login
      - /v1/signup
      - /v1/user/all # TODO: /v1/user/all을 excluded-paths에서 제외시키기
    integrated-services:
      uri: http://zylo-integrated-services:8081
      path:
        validation: /auth/jwt/validate
        login: /auth/login
        signup: /auth/signup
---
#개발용 설정
spring:
  config:
    activate:
      on-profile: dev

  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: integrated-services
              uri: http://localhost:8080
              predicates:
                - Path=/test
              filters:
                - RewritePath=/test, /ping

logging:
  level:
    root: info

server:
  port: 8082
  servlet:
    context-path: /

zylo:
  endpoints:
    excluded-paths:
      - /v1/login
      - /v1/signup
      - /v1/user/all # TODO: /v1/user/all을 excluded-paths에서 제외시키기
    integrated-services:
      uri: http://localhost:8081
      path:
        validation: /auth/jwt/validate
        login: /auth/login
        signup: /auth/signup