spring:
  profiles:
    default: prod
---
#배포용 설정
spring:
  config:
    activate:
      on-profile: prod

  application:
    name: api-gateway

logging:
  file:
    path: /var/www/api-gateway
  level:
    root: info

server:
  port: 8080
  servlet:
    context-path: /
---
#개발용 설정
spring:
  config:
    activate:
      on-profile: dev

  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        - id: drive-service
          uri: http://localhost:8080

logging:
  level:
    root: info

server:
  port: 8081
  servlet:
    context-path: /
