# 작성자: 이현민(id3ntity99)
# 내용  : github actions & docker를 이용한 CI/CD
name: Zylo Server CI/CD with Gradle & docker

on:
  push:
    paths:
      - "zylo-backend/chat-service/**"
    branches: ["main"]

jobs:
  ci-cd:
    runs-on: ubuntu-latest
    env:
      AWS_INSTANCE_SG_ID: ${{secrets.AWS_INSTANCE_SG_ID}}
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Change Permission for gradlew
        run: chmod +x ./zylo-backend/chat-service/gradlew

      - name: Gradle Build
        run: ./zylo-backend/chat-service/gradlew clean build

      - name: Docker build & push to Docker Hub
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/zylo-chat-service .  docker push ${{ secrets.DOCKER_USERNAME }}/zylo-chat-service

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_PRIVATE_KEY }}
          aws-region: ap-northeast-2
      - name: get runner ip address
        id: ip
        uses: haythem/public-ip@v1.2
      - name: whitelist runner ip address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: SSH into EC2 and deploy Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          port: 22
          script: |
            sudo docker ps
            sudo docker volume ls | grep zylo || sudo docker volume create zylo
            sudo docker stop zylo-chat-service || true && sudo docker rm zylo-chat-service || true
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/zylo-chat-service
            sudo docker run -d --name zylo-chat-service --memory=256m -e TZ=Asia/Seoul  -v zylo:/var/www/chat-service  -p 8082:8080 ${{ secrets.DOCKER_USERNAME }}/zylo-chat-service
            sudo docker image prune -f

      - name: revoke runner ip address
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32
